In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import pickle

In [2]:
file=pd.read_csv("housing.csv",header=None)

In [3]:
df=pd.DataFrame(file)
df

,0,1,2,3,4,5,6
0,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
1,79545.45857431678,5.682861321615587,7.009188142792237,4.09,23086.800502686456,1059033.5578701235,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
2,79248.64245482568,6.0028998082752425,6.730821019094919,3.09,40173.07217364482,1505890.91484695,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
3,61287.067178656784,5.865889840310001,8.512727430375099,5.13,36882.15939970458,1058987.9878760849,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
4,63345.24004622798,7.1882360945186425,5.586728664827653,3.26,34310.24283090706,1260616.8066294468,USS Barnett\nFPO AP 44820
...,...,...,...,...,...,...,...
4996,60567.944139865984,7.830362443635721,6.13735622764076,3.46,22837.361034746427,1060193.785884608,USNS Williams\nFPO AP 30153-7653
4997,78491.27543459789,6.999134987291412,6.576762660738709,4.02,25616.11548906122,1482617.728622024,"PSC 9258, Box 8489\nAPO AA 42991-3352"
4998,63390.68688550463,7.250590614779546,4.805080980291155,2.13,33266.145489652175,1030729.5831522895,"4215 Tracy Garden Suite 076\nJoshualand, VA 01..."
4999,68001.33123508695,5.534388416220344,7.130143864349472,5.44,42625.62015585088,1198656.8724076871,USS Wallace\nFPO AE 73316
5000,65510.581803666224,5.992305307333977,6.792336104424982,4.07,46501.28380314165,1298950.4802669554,"37778 George Ridges Apt. 509\nEast Holly, NV 2..."

In [4]:
column_name=['Income','House age','Number of rooms','Number of bedrooms','Population','Price','Address']

In [5]:
df.columns=column_name
df

,Income,House age,Number of rooms,Number of bedrooms,Population,Price,Address
0,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
1,79545.45857431678,5.682861321615587,7.009188142792237,4.09,23086.800502686456,1059033.5578701235,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
2,79248.64245482568,6.0028998082752425,6.730821019094919,3.09,40173.07217364482,1505890.91484695,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
3,61287.067178656784,5.865889840310001,8.512727430375099,5.13,36882.15939970458,1058987.9878760849,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
4,63345.24004622798,7.1882360945186425,5.586728664827653,3.26,34310.24283090706,1260616.8066294468,USS Barnett\nFPO AP 44820
...,...,...,...,...,...,...,...
4996,60567.944139865984,7.830362443635721,6.13735622764076,3.46,22837.361034746427,1060193.785884608,USNS Williams\nFPO AP 30153-7653
4997,78491.27543459789,6.999134987291412,6.576762660738709,4.02,25616.11548906122,1482617.728622024,"PSC 9258, Box 8489\nAPO AA 42991-3352"
4998,63390.68688550463,7.250590614779546,4.805080980291155,2.13,33266.145489652175,1030729.5831522895,"4215 Tracy Garden Suite 076\nJoshualand, VA 01..."
4999,68001.33123508695,5.534388416220344,7.130143864349472,5.44,42625.62015585088,1198656.8724076871,USS Wallace\nFPO AE 73316
5000,65510.581803666224,5.992305307333977,6.792336104424982,4.07,46501.28380314165,1298950.4802669554,"37778 George Ridges Apt. 509\nEast Holly, NV 2..."

In [6]:
encode=LabelEncoder()

In [7]:
df['Address']=encode.fit_transform(df['Address'])
df

,Income,House age,Number of rooms,Number of bedrooms,Population,Price,Address
0,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,4486
1,79545.45857431678,5.682861321615587,7.009188142792237,4.09,23086.800502686456,1059033.5578701235,962
2,79248.64245482568,6.0028998082752425,6.730821019094919,3.09,40173.07217364482,1505890.91484695,863
3,61287.067178656784,5.865889840310001,8.512727430375099,5.13,36882.15939970458,1058987.9878760849,4069
4,63345.24004622798,7.1882360945186425,5.586728664827653,3.26,34310.24283090706,1260616.8066294468,4795
...,...,...,...,...,...,...,...
4996,60567.944139865984,7.830362443635721,6.13735622764076,3.46,22837.361034746427,1060193.785884608,4751
4997,78491.27543459789,6.999134987291412,6.576762660738709,4.02,25616.11548906122,1482617.728622024,4637
4998,63390.68688550463,7.250590614779546,4.805080980291155,2.13,33266.145489652175,1030729.5831522895,1897
4999,68001.33123508695,5.534388416220344,7.130143864349472,5.44,42625.62015585088,1198656.8724076871,4834
5000,65510.581803666224,5.992305307333977,6.792336104424982,4.07,46501.28380314165,1298950.4802669554,1703

In [8]:
'''df['Price'].replace('?',np.nan,inplace=True)
df['Price']=df['Price'].apply(pd.to_numeric,errors='ignore')
df['Price'].fillna(df['Price'].mean(),inplace=True)
df['Population'].fillna(df['Population'].mean(),inplace=True)'''

"df['Price'].replace('?',np.nan,inplace=True)\ndf['Price']=df['Price'].apply(pd.to_numeric,errors='ignore')\ndf['Price'].fillna(df['Price'].mean(),inplace=True)\ndf['Population'].fillna(df['Population'].mean(),inplace=True)"

In [9]:
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
df1 = df[~((df< (Q1 - 1.5 * IQR)) |(df > (Q3 + 1.5 * IQR))).any(axis=1)]
df1
'''
df = df[(df[i] >= Q1-1.5*IQR) & (df[i] <= Q3 + 1.5*IQR)]
'''

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [ ]:
# Assume the price is in cents and you want to convert to dollars
df['Price'] = df['Price'] / 100  # Convert cents to dollars if that's the case

# Format the 'Price' column to a more readable format, like rounding to two decimal places
df['Price'] = df['Price'].round(2)
df

,Income,House age,Number of rooms,Number of bedrooms,Population,Price,Address
0,79545.45857,5.682861,7.009188,4.09,23086.80050,10590.34,962
1,79248.64245,6.002900,6.730821,3.09,40173.07217,15058.91,863
2,61287.06718,5.865890,8.512727,5.13,36882.15940,10589.88,4069
3,63345.24005,7.188236,5.586729,3.26,34310.24283,12606.17,4794
4,59982.19723,5.040555,7.839388,4.23,26354.10947,12321.93,4736
...,...,...,...,...,...,...,...
4995,60567.94414,7.830362,6.137356,3.46,22837.36103,10601.94,4750
4996,78491.27543,6.999135,6.576763,4.02,25616.11549,14826.18,4636
4997,63390.68689,7.250591,4.805081,2.13,33266.14549,10307.30,1897
4998,68001.33124,5.534388,7.130144,5.44,42625.62016,11986.57,4833
4999,65510.58180,5.992305,6.792336,4.07,46501.28380,12989.50,1703

In [ ]:
x=df1.drop('Price',axis=1)
y=df1['Price']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [ ]:
scaler=StandardScaler()
scaler.fit(x_train,y_train)

StandardScaler()

In [ ]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
print(model.score(x_train,y_train)*100)
print(model.score(x_test,y_test)*100)

91.22184801380308
90.75462270744204

In [ ]:
savedfile=open('housingmodel.pklz','wb')
pickle.dump(model,savedfile)

In [ ]:
readfile=open('housingmodel.pklz','rb')
newmodel=pickle.load(readfile)
newmodel.score(x_test,y_test)

0.9081178667870534